name: Node CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: pnpm/action-setup@0ebf47130e4866e96fce0953f49152a61190b271 # v6.0.9
      - uses: actions/setup-node@v6
        with:
          node-version: 24
          cache: pnpm
      - run: pnpm install
      - run: pnpm install --frozen-lockfile
      - run: pnpm vp --version
      - run: pnpm test
      - run: pnpm build
      - uses: actions/upload-artifact@v7
        with:
          path: ./dist
      - uses: peaceiris/actions-gh-pages@v4
        if: github.event_name == 'push' && github.ref == 'refs/heads/master'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          force_orphan: true
