name: Python CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          python-version: '3.9'
      - name: Install dependencies
        run: uv sync
      - name: Test with doctest
        run: uv run python -m doctest -v backend/location_to_wikitext.py
